"""Backbone-conditioned Pareto analysis for preference-aware IDS defense selection.

Public API of the package.  Experiment runners import from here, which keeps
``code/run_*.py`` and the analysis scripts thin and consistent::

    from ids_defense_selection import ExperimentConfig, MLPBackbone, train_all_defenses
"""
from .attacks import (
    ATTACK_NAMES,
    apgd_attack,
    clamp_numeric,
    compute_attack_validity_metrics,
    count_out_of_range,
    cw_attack,
    fgsm_attack,
    generate_adversarial_examples,
    max_violation,
    pgd_attack,
)
from .backbones import (
    CNN1DBackbone,
    FTTransformerBackbone,
    FT_TRANSFORMER_KWARGS,
    MLPBackbone,
    build_ft_transformer,
)
from .config import (
    ExperimentConfig,
    add_config_arguments,
    build_parser,
    config_from_args,
    emit_config,
    parse_args,
    parse_tuple_value,
    resolve_path,
)
from .data import (
    build_features,
    load_unsw_nb15,
    make_dataloader,
    numpy_to_torch,
    set_seed,
    stratified_subset_indices,
)
from .defenses import (
    DEFENSE_ORDER,
    OPTIONAL_DEFENSES,
    TrainedDefenses,
    compute_class_aware_sensitivity_mask,
    compute_progressive_masks,
    compute_sensitivity_mask,
    compute_sensitivity_weights,
    fit_class_aware_constrained,
    fit_dst_sa_trades,
    fit_free_at,
    fit_progressive_class_aware,
    fit_reference_models,
    fit_sa_trades,
    fit_supervised,
    fit_trades,
    summarize_training_budget,
    train_all_defenses,
)
from .evaluation import (
    EvaluationResults,
    EvaluationSet,
    classification_metrics,
    count_parameters,
    evaluate_attack_suite,
    evaluate_category_recall,
    evaluate_defenses,
    evaluate_model_on_attack,
    evaluate_transfer_attack,
    measure_inference_cost,
    predict_proba,
)
from .experiment import EVAL_SUBSET_SEED, prepare_attack_categories, run_mlp_experiment
from .reporting import (
    BackboneRunFrames,
    compute_significance_tests,
    plot_clean_f1_bar,
    plot_efficiency_tradeoff,
    plot_metric_curve,
    plot_ratio_ablation,
    plot_transfer_heatmap,
    summarize_results,
    write_backbone_outputs,
)

__all__ = [
    "ATTACK_NAMES",
    "BackboneRunFrames",
    "CNN1DBackbone",
    "DEFENSE_ORDER",
    "EVAL_SUBSET_SEED",
    "ExperimentConfig",
    "EvaluationResults",
    "EvaluationSet",
    "FTTransformerBackbone",
    "FT_TRANSFORMER_KWARGS",
    "MLPBackbone",
    "OPTIONAL_DEFENSES",
    "TrainedDefenses",
    "add_config_arguments",
    "apgd_attack",
    "build_features",
    "build_ft_transformer",
    "build_parser",
    "classification_metrics",
    "clamp_numeric",
    "compute_attack_validity_metrics",
    "compute_class_aware_sensitivity_mask",
    "compute_progressive_masks",
    "compute_sensitivity_mask",
    "compute_sensitivity_weights",
    "compute_significance_tests",
    "config_from_args",
    "count_out_of_range",
    "count_parameters",
    "cw_attack",
    "emit_config",
    "evaluate_attack_suite",
    "evaluate_category_recall",
    "evaluate_defenses",
    "evaluate_model_on_attack",
    "evaluate_transfer_attack",
    "fgsm_attack",
    "fit_class_aware_constrained",
    "fit_dst_sa_trades",
    "fit_free_at",
    "fit_progressive_class_aware",
    "fit_reference_models",
    "fit_sa_trades",
    "fit_supervised",
    "fit_trades",
    "generate_adversarial_examples",
    "load_unsw_nb15",
    "make_dataloader",
    "max_violation",
    "measure_inference_cost",
    "numpy_to_torch",
    "parse_args",
    "parse_tuple_value",
    "pgd_attack",
    "plot_clean_f1_bar",
    "plot_efficiency_tradeoff",
    "plot_metric_curve",
    "plot_ratio_ablation",
    "plot_transfer_heatmap",
    "predict_proba",
    "prepare_attack_categories",
    "resolve_path",
    "run_mlp_experiment",
    "set_seed",
    "stratified_subset_indices",
    "summarize_results",
    "summarize_training_budget",
    "train_all_defenses",
    "write_backbone_outputs",
]
